Profile/urls.py
from django.urls import include, re_path
from Profile.views import ProfileView, allagents
from .import views


app_name = 'Profile'

urlpatterns = [
    re_path(r'^Profile/$', ProfileView.as_view(), name='Profile'),
    re_path(r'^Profile/(?P<pk>\d+)/$', ProfileView.as_view(), name='view_profile_with_pk'),
    re_path(r'^allagents/$', views.allagents, name='allagents'),

]

agent/urls.py
from django.conf.urls import include, re_path
from .import views
from .views import all_agents, agent, agentadmin ,Post, Messages


app_name = 'agent'

urlpatterns = [
    re_path(r'^all_agents/$', views.all_agents, name='all_agents'),
    re_path(r'^agent/$', views.agent, name='agent'),
    re_path(r'^agentadmin/$', views.agentadmin, name='agentadmin'),
    re_path(r'^post/$', views.Post, name='post'),
    re_path(r'^messages/$', views.Messages, name='messages')

]

sci/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include ,path ,re_path

from login.views import  client, login, agent

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('login.urls')),
    #path('chat/', include('chat.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', login.SignUpView.as_view(), name='signup'),
    path('accounts/signup/client/', client.ClientSignUpView.as_view(), name='client_signup'),
    path('accounts/signup/agent/', agent.AgentSignUpView.as_view(), name='agent_signup'),
    path('home/', include('home.urls', namespace='home')),
    path('agent/', include('agent.urls', namespace='agent')),
    path('document/', include('document.urls', namespace='document')),
    path('Profile/',include('Profile.urls',namespace='Profile')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

Profile/models.py
from django.db import models
# Create your models here.

agent/models.py
from django.db import models
from login.models import User

# Create your models here.

class Chat(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    message = models.FileField(upload_to='documents/')

    def __unicode__(self):
        return self.message

Profile/forms.py
from django import forms
from django.contrib.auth.forms import  UserChangeForm, UserCreationForm
from login.models import User, Agent, Client
from mapwidgets.widgets import GooglePointFieldWidget


class AgentForm(forms.ModelForm):

    class Meta:
        model = Agent

        fields = [
            'business_name',
            'county',
            'sub_county',
            'Estate',
            'location',
            'address',
            'phone',
            'image'
        ]

    def save(self, user=None):
        agent = super(AgentForm, self).save(commit=False)
        if user:
            agent.user = user
        agent.save()
        return agent


#class AgentAdminForm(forms.ModelForm):
#    class Meta:
#        model = location
#        fields = ("coordinates", "city_hall")
#        widgets = {
#                    'coordinates': GooglePointFieldWidget,
#        'city_hall': GooglePointFieldWidget,
#        }

Profile/views.py
from django.views.generic import TemplateView
from django.http import Http404
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.urls import reverse_lazy 
from random import randint
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.utils.decorators import method_decorator
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from types import MethodType
from operator import attrgetter


class ProfileView(TemplateView):
    template_name = 'Profile/Profile.html'

    def get(self, request, category_slug=None, pk=None):
        category = None
        context = {}

        if pk:
            category = None
            user = User.objects.get(pk=pk)
        
        else:
            category = None
            user = request.user

        args = {
            'user' : user, 'category' : category
        }   
        return render(request, self.template_name, args)


def allagents(request):

    try:

        users = User.objects.exclude(id=request.user.id)
    except:
        users = User.objects.all()
    

    return render(request, 'Profile/shop.html', {'users': users})

agent/views.py
from django.shortcuts import render
from sci import settings 
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView
from django.views.decorators.http import require_POST
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from login.models import User 
#from .filters import UserFilter
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse, JsonResponse
from django.db import IntegrityError
from .models import Chat

def all_agents(request):
    
    return render(request, 'agent/all_agents.html')

def agent(request):
    
 
    return render(request,'agent/agent.html')

#def Git(request):
 #   return render(request, )

def agentadmin(request):
    c = Chat.objects.all()
    return render(request, 'agent/agentadmin.html', {'agentadmin': 'active', 'chat': c})


def Post(request):
    message = msg
    if request.method == "POST":
        msg = request.POST.get('msgbox', None)
        c = Chat(id=request.user.id)
        if msg != '':
            c.save()
        return JsonResponse({ 'msg': msg, 'user': c.user.username })
    else:
        return HttpResponse('Request must be a POST!')



def Messages(request):
    c = Chat.objects.all()
    return render(request, 'agent/message.html', {'chat': c})

login/views/agent.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator


from login.decorators import client_required, agent_required
from login.models import Agent, User
from django.views.generic import TemplateView , CreateView
from login.forms import AgentSignUpForm


class AgentSignUpView(CreateView):
    template_name = 'registration/signup_form.html'
    model = Agent
    form_class = AgentSignUpForm

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'agent'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('agent:product_list')

Profile/templates/Profile/Profile.html
{% extends "base.html" %}  

    { {% block head %}
    <title>{{ user.agent.business_name }}</title>
{% endblock head %}}
 {% block body %} 
<!--navbar with profile element tabs user authentication is necessary for security-->
<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:black;">
         
          

      <!-- Small button groups (default and split) -->
<div class="btn-group">
  <button class="btn text-white btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    {{ user.agent.business_name }}
  </button>
  <div class="dropdown-menu">
          <a class=" dropdown-item" href="#">Welcome to {{ user.agent.business_name }} </a>
         

  </div>
</div>   
 

</nav>



<br/>

  <div class="container">
            <div class="mw-100 p-2 card  border-0" style="width: 70.5rem;">
                <img class="border border-grey rounded-circle align-centre"  src="{% if user.agent.image %}
                              {{ user.agent.image.url  }}{% else %}{% endif  %}
                              " class="img-responsive" alt="no image" style="width:7rem; height:6.5rem; " alt="Card image cap">
                <div class="card-body">
                  <h3 class="card-title center"> <b>{{ user.agent.Business_name }}</b></h3>
                  <p class="card-text font-italic " style="color:red;"><p>{{ user.agent.location }}</p></p>
                  <p class="card-text font-italic " style="color:red;"><p>{{ user.agent.address }}</p></p>
                  <p class="card-text font-italic " style="color:red;"><p>{{ user.agent.phone }}</p></p>
                  <p class="card-text">
              
                  
                  <!--<p><b>Email </b>  : {{ user.email }}</p>-->
                  
            
                  
                </div>
              </div>
            </div>   
          </div>
<!--end profile column -->
        <div class="col-12 col-sm-6 col-md-9" style="color:rgb(21, 20, 13)">

  



</div>
      </div>


<br>


</div>

<br/>
{% include "pagination.html" %} 




<br>
<hr/>
<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; Notehub &middot; <a href="{% url 'home:privacy' %}">Privacy</a>  <a href="{% url 'home:terms' %}">Terms</a></p>
</footer> 


{% endblock body %} 

Profile/templates/Profile/agents.html
{% extends "base.html" %} 

{ {% block head %}
    <title>All Agents</title>
{% endblock head %}}

{% block body %}

<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:black;"><b>All Agents</b></nav>
<br/>



    <div class="row no-gutters">
    <!--fist part-->
            <div class="col-12 col-sm-6 col-md-3">

          

            
            </div>
    <!--end fisrt part-->

<!--second secton-->
        <div class="col-12 col-sm-6 col-md-9" style="color:rgb(21, 20, 13)">



        
       <div class="container"> 
       {% for user in users %}   
       {% if user.is_staff %}   
       {% if user.is_agent %}   
          <div class=" ">
                
                <div class=" mw-100 card  " style="width: 62rem; ">
          
          
          
          <div class="card-body " >
              
                    <div class="row">
                                <div class="col-12 col-md-3">
                                    <a href="{% url 'Profile:view_profile_with_pk' pk=user.pk %}">
                            
                            
                                         <img class="border border-grey rounded" src="{% if user.agent.image %}
                                                     {{ user.agent.image.url  }}{% else %}{% endif  %}
                                                    " class="img-responsive" alt="no image" style="width:5.5rem; height:6.5rem;">
                            
                            
                            
                                    </a>
                                </div>
                                <div class="col-12 col-md-3">
                                     
                                    <a href="{% url 'Profile:view_profile_with_pk' pk=user.pk %}">
                                            <b>{{ user.agent.Business_name|truncatechars:100 }}</b> 
                                    </a>
                                    </br>
                                     
                                   <a>
                                            <p><b>contacts:</b> {{ user.agent.phone|truncatechars:100 }}</p>
                                    </a>  
                                        


                                </div>
                                <div class="col-12 col-md-6">
                                <h6 style="color:teal;"><b>Description</b></h6>
                                       <p style="color:black;">{{ user.agent.description|truncatechars:100 }}</p>

                         
     

                                </div>
                    </div>


               
           
        
          
         </div>
         
</div>

         
        </div>
        {% else %}


 


        {% endif %}
       {% endif %}
 {% endfor %}






      </div>

 


<!--end second section-->


    <br/>


{% endblock body %}

Profile/templates/Profile/location.html
{% extends "base.html" %}  

{% block head %}
<head>

{{ form.media }}
</head>
{% endblock head %}