Profile/urls.py
from django.urls import include, re_path
from Profile.views import ProfileView, allagents
from .import views


app_name = 'Profile'

urlpatterns = [
    re_path(r'^Profile/$', ProfileView.as_view(), name='Profile'),
    re_path(r'^Profile/(?P<pk>\d+)/$', ProfileView.as_view(), name='view_profile_with_pk'),
    re_path(r'^allagents/$', views.allagents, name='allagents'),

]

login/urls.py
from django.urls import include, path

from .views import login, client, agent

from django.conf.urls import url
from django.urls import include, re_path
from django.urls import include ,path
from django.contrib.auth.views import (
    login,
    logout,
     password_reset_confirm,
      password_reset,
     password_reset_done,
     password_reset_complete
     )
from django.contrib.auth import views as auth_views
from . import views as myapp_views
from . import views
from  .views import login 

app_name = 'login'

urlpatterns = [

    path('clients/', include(([
        re_path(r'^profile/$',login.ProfileView.as_view(), name='profile'),
        re_path(r'^profile/edit/$', login.edit_profile, name='edit_profile'),
        re_path(r'^change-password/$', login.change_password, name='change_password'),
        re_path(r'^reset-password/$', password_reset,{ 'template_name':
                  'login/reset_password.html','post_reset_redirect':
                  'login:password_reset_done','email_template_name':
                  'login:reset_password_email.html' }, name='reset_password'),
        re_path(r'^reset-password/done/$', password_reset_done, 
                  {'template_name':'login/reset_password_done.html'},
                  name='password_reset_done'),
        re_path(r'^reset-password/confirm/$', password_reset_confirm, name='password_reset_confirm'),

        re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                  password_reset_confirm, {'template_name':
                  'login/reset_password_confirm.html', 'post_reset_redirect':
                  'login:password_reset_complete'},  name='password_reset_confirm'),

        re_path(r'^reset-password/complete/$', password_reset_complete,{'template_name':
                  'login/reset_password_complete.html'}, name='password_reset_complete'),
        re_path(r'^logout/$', logout,{'template_name': 'login/logout.html'}, name='logout'),

        re_path(r'^about/$', login.about, name='about'),
        #re_path(r'^delete/(?P<username>[\w|\W.-]+)/$', views.delete_user, name='delete-user')

    ]))),


    path('agent/', include(([
        #re_path(r'^profile/$',login.ProfileView.as_view(), name='profile'),
        re_path(r'^profile/edit/$', login.edit_profile, name='edit_profile'),
        re_path(r'^change-password/$', login.change_password, name='change_password'),
        
        re_path(r'^reset-password/$',  password_reset,{ 'template_name':
                  'login/reset_password.html','post_reset_redirect':
                  'login:password_reset_done','email_template_name':
                  'login/reset_password_email.html' }, name='reset_password'),
        re_path(r'^reset-password/done/$', password_reset_done, 
                  {'template_name':'login/reset_password_done.html'},
                  name='password_reset_done'),
        re_path(r'^reset-password/confirm/$', password_reset_confirm, name='password_reset_confirm'),
  
        re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                  password_reset_confirm, {'template_name':
                  'login/reset_password_confirm.html', 'post_reset_redirect':
                  'login:password_reset_complete'},  name='password_reset_confirm'),

        re_path(r'^reset-password/complete/$', password_reset_complete,{'template_name':
                  'login/reset_password_complete.html'}, name='password_reset_complete'),
        re_path(r'^logout/$', logout,{'template_name': 'login/logout.html'}, name='logout'),

        re_path(r'^about/$', login.about, name='about')

    ])))
 
]





    

sci/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include ,path ,re_path

from login.views import  client, login, agent

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('login.urls')),
    #path('chat/', include('chat.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', login.SignUpView.as_view(), name='signup'),
    path('accounts/signup/client/', client.ClientSignUpView.as_view(), name='client_signup'),
    path('accounts/signup/agent/', agent.AgentSignUpView.as_view(), name='agent_signup'),
    path('home/', include('home.urls', namespace='home')),
    path('agent/', include('agent.urls', namespace='agent')),
    path('document/', include('document.urls', namespace='document')),
    path('Profile/',include('Profile.urls',namespace='Profile')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

Profile/models.py
from django.db import models
# Create your models here.

login/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import escape, mark_safe
from django.utils import timezone
from sci import settings
from django.db.models.signals import post_save


class User(AbstractUser):
    is_client = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Business_name = models.CharField(max_length=21, default='')
    county = models.CharField(max_length=100, default='')
    sub_county = models.CharField(max_length=100, default='')
    Estate = models.CharField(max_length=100, default='')
    location = models.CharField(max_length=100, default='')
    address = models.CharField(max_length=50, default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True, default='0')

    def __str__(self):
        return self.user.username


class Client(models.Model):
    
    phone = models.IntegerField(default=0)
    county = models.CharField(max_length=100,blank=True, null=True, default='',choices=(
                                    ('Nairobi', 'Nairobi'),  
                                    ('Nakuru', 'Nakuru')))
    image = models.ImageField(upload_to='profile_image', blank=False ,default='')
    gender = models.CharField(max_length=6,blank=True, null=True, default='',choices=(
                                    ('M', 'Male'),  
                                    ('F', 'Female')))
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

Profile/forms.py
from django import forms
from django.contrib.auth.forms import  UserChangeForm, UserCreationForm
from login.models import User, Agent, Client
from mapwidgets.widgets import GooglePointFieldWidget


class AgentForm(forms.ModelForm):

    class Meta:
        model = Agent

        fields = [
            'business_name',
            'county',
            'sub_county',
            'Estate',
            'location',
            'address',
            'phone',
            'image'
        ]

    def save(self, user=None):
        agent = super(AgentForm, self).save(commit=False)
        if user:
            agent.user = user
        agent.save()
        return agent


#class AgentAdminForm(forms.ModelForm):
#    class Meta:
#        model = location
#        fields = ("coordinates", "city_hall")
#        widgets = {
#                    'coordinates': GooglePointFieldWidget,
#        'city_hall': GooglePointFieldWidget,
#        }

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.db import transaction
from django.forms.utils import ValidationError
from django.contrib.auth import get_user_model
from login.models import User, Client, Agent


class ClientSignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )
        
        @transaction.atomic
        def save(self, commit=True):
            user = super(ClientSignUpForm, self).save(commit=False)
            User.username = self.cleaned_data['username']
            User.email = self.cleaned_data['email']
            user.is_client = True
            if commit:
                user.save()
            return user



class AgentSignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

        def save(self, commit=True):
            user = super(AgentSignUpForm, self).save(commit=True)
            User.username = self.cleaned_data['username']
            User.email = self.cleaned_data['email']
            user.is_agent = True
            if commit:
                user.save()
            return user



class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        )


class EditAgentForm(UserChangeForm):

    class Meta:
        #model = EditShopForm
        fields = (
            'Business_name',
            'description',
            'image',
            'county',
            'sub_county',
            'estate',
            'location',
            'Address',
            'phone'
            

        )

Profile/views.py
from django.views.generic import TemplateView
from django.http import Http404
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.urls import reverse_lazy 
from random import randint
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.utils.decorators import method_decorator
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from types import MethodType
from operator import attrgetter


class ProfileView(TemplateView):
    template_name = 'Profile/Profile.html'

    def get(self, request, category_slug=None, pk=None):
        category = None
        context = {}

        if pk:
            category = None
            user = User.objects.get(pk=pk)
        
        else:
            category = None
            user = request.user

        args = {
            'user' : user, 'category' : category
        }   
        return render(request, self.template_name, args)


def allagents(request):

    try:

        users = User.objects.exclude(id=request.user.id)
    except:
        users = User.objects.all()
    

    return render(request, 'Profile/shop.html', {'users': users})

login/views/agent.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator


from login.decorators import client_required, agent_required
from login.models import Agent, User
from django.views.generic import TemplateView , CreateView
from login.forms import AgentSignUpForm


class AgentSignUpView(CreateView):
    template_name = 'registration/signup_form.html'
    model = Agent
    form_class = AgentSignUpForm

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'agent'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('agent:product_list')

login/views/client.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator



from login.decorators import client_required
from login.models import  Client, User
from django.views.generic import TemplateView , CreateView
from login.forms import  ClientSignUpForm


class ClientSignUpView(CreateView):
    template_name = 'registration/signup_form.html'
    model = Client
    form_class = ClientSignUpForm

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'client'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('login:about')

login/views/login.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView

from django.http import Http404
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404
#from django.contrib.auth.forms import RegistrationForm
#from login.forms import ( EditProfileForm)
#from django.contrib.auth.models import User
from ..models import User

from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm#, EditProfileForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from login.forms import  EditProfileForm#, contactForm
#from home.views import Post
#from home.models import  Friend
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
#from login.models import UserProfile
#from shopp.models import Product, Category

from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import get_template




class SignUpView(TemplateView):
    template_name = 'registration/signup.html'

    def home(self, request):
        if request.user.is_authenticated:
            if request.user.is_shop:
                return redirect('login:about')
            else:

            
                return redirect('login:about')
            if request.user.is_client:

                return redirect('login:about')
            
            else:
                return redirect('login:about')
        
        return render(request,'login/about.html')

#    def get(self, request):
#        if request.user.is_authenticated:
#            if request.user.is_client:
##                return redirect('shopp:product_list')
 #           else:
#                return redirect('shopp:product_list')
#        return render(request,'registration/signup.html')




@method_decorator(login_required, name='dispatch')
class ProfileView(TemplateView):
    template_name = 'login/profile.html'
    
    def get(self, request):
       

        try:
            users = User.objects.exclude(id=request.user.id)
            friend = Friend.objects.get(current_user=request.user)
            friends = friend.users.all()

        except:
            users = User.objects.all()
            friends = Friend.objects.all()
        args = {
                 #'user': user,
                 'users': users,
         'friends': friends
        }
        return render(request, self.template_name, args)

    




@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect( 'login:profile' )

    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'login/edit_profile.html', args)
        
@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST,user=request.user )

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)

            return redirect( 'login:profile' )

        else:
            return redirect('/login/change-password')

    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'login/edit_profile.html', args)




def about(request):
    context = locals()
    #template = 'about.html'
    #form = contactForm(request.POST or None)
#
#    if form.is_valid():
#        print( request.POST)
#        context = locals()
    return render(request, 'login/about.html')#,context )
 


@login_required
def login_admin(request):
    return render(request, 'admin/login.html')


@login_required
def delete_user(request, username):
    context = {}
    try:
        u = User.objects.get(username=username)
        u.delete()
        context['msg'] = 'The user is deleted.'       
    except User.DoesNotExist: 
        context['msg'] = 'User does not exist.'
    except Exception as e: 
        context['msg'] = e.message

    return render(request, 'template.html', context=context) 

login/templates/login/about.html
{% extends "base.html" %}


{{%  block head %}
<title>about</title>
{% endblock head  %}}

{% block body %}
<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:teal;">about favourite</nav>
<div class="jumbotron">
     <h6>favourite is a plartform created to and for easy and quality shopping.There are a no of shops in the site and many more will be available in the
     coming months.We expect to enroll more than a hundred shops by the end of the year.Upon login a user is able to access a viriety of products and shops offering those products in nairobi.
      The user also enjoy the privilede of adding shops to his/her favourite list for asier access and update of shops. Shops on the plartform also enjoy 
      the priledge of updating their clients on new products that they have bo=rought in the market and thi will result in increased sales. We urge all shops to strictly adher to 
      favourite's terms and conditions' 
     </h6>

</div>


{% endblock body %} 

login/templates/login/accounts.html
 {% extends "base.html" %}   
    
 {% load crispy_forms_tags %}

 {{%  block head %}
<title>Login to Favourite</title>
{% endblock head  %}}

{% block body %}

<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:teal;"><h6>Welcome</h6></nav>
<br/>
<div class="container">
<div class="row">
    <div class="col-3 col-md col-md-3">
        <div class="container">
          <h4></h4>
        </div>
            
        </div>

            <!--section 2-->
        <div class="col-12 col-sm-6 col-md-6" >
            
           <h2>Login</h2><b>
           <form method="POST">
              {% csrf_token %}   
              {{ form|crispy }}
              <button type="submit" class="btn btn-primary" name="button">Sign In</button>          
           </form>
        </b>
        <br/>
        <a href="{% url 'login:reset_password'  %}"><h5>Forgot password?</h5> </a>
        <a  href="{% url 'login:register'  %}"> <h5> Sign Up</h5></a>
        
           </div>

            </div>

            <div class="col-3 col-md col-md-3">
                <div class="container" style="color:olive;"><h4></h4>
              
                  </div>
                </div>
        



<br>
<hr/>
<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; Favourite &middot; <a href="{ % url 'home:privacy' %}">Privacy</a> Favourite <a href="{% url 'home:terms' %}">Terms</a></p>
</footer> 


<!--<div class="rights">
    <h6 class="container">2018 © machua martin</h6>
</div>
</div>-->
{% endblock body %}

login/templates/login/edit_profile.html
{% extends "base.html" %}  
{% load crispy_forms_tags %}
    { {% block head %}
    <title>Profile</title>
{% endblock head %}}
 {% block body %}

 <nav class="navbar navbar-expand text-white shadow navbar " style="background-color:teal;">
        <button type="button"  class="btn btn-sm text-white "  aria-haspopup="true" aria-expanded="false">
                    <a class=" btn-sm text-white"href="{% url 'login:edit_profile'  %}">Edit Profile</a>
                  </button>
  
    </nav>

 <br />


<!--dividing into 3 columns-->
<div class="row">
    <!--first column-->
    <div class="col-md-3"></div>
    <!--end fisrt column-->
    <!--second column-->
    <div class="col-md-6">
            <div class="alert alert-danger" role="alert"><p>Want to edit your profile?? You can edit your profile here!!!</p></div>
                       <form method="POST">
                           {% csrf_token %} 
                           {{ form|crispy }}
                           <br />
                           <button type="submit" class="btn btn-danger outline">Submit</button>
                       </form>
            </div>              
    </div>
    <!--end second column-->
    <!--third column-->
    <div class="col-md-3"></div>
    <!--end third column-->
</div>
<br/>
<hr/>
<!--Footer-->
<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; Martin Machua &middot; <a href="#">Privacy</a> Comparisonn <a href="#">Terms</a></p>
</footer> 
<!--end footer-->
{% endblock body %} 

login/templates/login/logout.html
{% extends "base.html" %} 

{{%  block head %}
<title>You have logged out</title>
{% endblock head  %}}
{% block body %}

<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:teal;">
    <h5> thank you for your time {{ user.username }} </h5></nav>
</div>
<div class="container">
    <div class="col-sm-6 col-sm-offset-3">
<br/>
<p class="alert alert-danger" role="alert">
    you have logged out successfully !!!!
</p>
   
   <a href="{ % url 'login:login' %}"  type="button" class="btn btn-outline-success" role="button">login again</a>   
    
</form>
</div>
</div>
{% endblock body %}
 

login/templates/login/profile.html
{% extends "base.html" %}

    { {% block head %}
    <title>Profile</title>
{% endblock head %}}
 {% block body %} 
<!--navbar with profile element tabs user authentication is necessary for security-->
 
<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:teal;">
    {% if user.is_authenticated %}
    <div class="dropdown">
        <button class="btn btn-sm  dropdown-toggle text-white" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color:teal;">
         Edit profile
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
        
         <!-- <a class="nav-item nav-link dropdown-item " href="{% url 'Profile:Clientform'  %}">create Profile</a>-->
          
          <a class="nav-item nav-link dropdown-item " href="{% url 'Profile:editclient' %}">profile</a>
      
          
          <a class="nav-item nav-link dropdown-item " href="{% url 'login:edit_profile'  %}">Edit Profile</a>
          <a class="nav-item nav-link dropdown-item " href="{% url 'login:change_password'  %}">Change Password</a>
          <a class="nav-item nav-link dropdown-item " href="{% url 'login:logout' %}">Logout</a>
        </div>
      </div>
      {% endif %}

<a href="{% url "Profile:favouriteshops" %}"  class="btn btn-sm text-white btn-outline" >
   Favourite shops
  </a>
   
</nav>
   
<br/>




    <div class="row no-gutters">
        <div class="col-12 col-sm-6 col-md-3">

          <div class="container">
            <div class=" mw-100 p-2 card  border-0 " style="width: 21.5rem;">
             
                <img class="card-img-top" src="{% if user.client.image %}
                              {{ user.client.image.url  }}{% else %}{% endif  %}
                              " class="img-responsive" alt="no image"  style="width:21.2.5rem; height:15rem; " >
              
                <div class="card-body">
                  <h5 class="card-title center"> <b>{{ user }}</b></h5>
                  <p class="card-text font-italic " style="color:red;"><p>{{ user.client.description }}</p></p>
                  <p class="card-text">
              <hr>
                  
                  <p><b>Email </b>  : {{ user.email }}</p>
                  
                  <p><b>City </b>: {{ user.client.city }}</p>
                  <p><b>Contacts</b>: {{ user.client.phone }}</p>
              
        
                  
                </div>
              </div>
            </div>


            
          </div>

        <div class="col-12 col-sm-6 col-md-6" style="color:rgb(21, 20, 13)">


       <div class="container"> 
       
       <div class=" row"   >
         {% for user_post in user_posts %}
          <div class=" card   mb-3  border-0" style="width: 20.24rem; height:28.24rem; display:table-row"  >
              <div class="card-header " >
                 
               <!--<a class="mr-auto " href="{% url 'login:view_profile_with_pk' pk=user.pk %}"> <b>{{ user_post.user.username }} </b> </a>-->
                
              </div>
              <div class="card-body ">
                {% if user_post.image %}
                <p class="card-text border-dark" > 
                  <a href="{{ user_post.get_absolute_re_path }}">  
                    <img src="{% if user_post.image %}{{ user_post.image.url  }}{% else %}{% endif  %}" class="mw-100 rounded border-dark" style="width: 20.24rem; height:20.24rem; ">
                  </a>
                </p>{% endif %}
              </div>
              <div class="card-footer bg ">

            
              </div>
              
            </div>
          
        {% endfor  %} 
      </div>
  </div>
</div>



<div class="col-12 col-sm-6 col-md-3">

       

</div>


      












</div>
<br>
<hr>
<footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; Favourite &middot; <a href="{% url 'home:privacy' %}">Privacy</a> Favourite <a href="{% url 'home:terms' %}">Terms</a></p>
  </footer> 


{% endblock body %} 

login/templates/login/reg_form.html
{% extends "base.html" %} 
{% load crispy_forms_tags %} 

{{%  block head %}
<title>Signup</title>
{% endblock head  %}}
    
        {% block body %}
        <nav class="navbar navbar-expand text-white shadow navbar " style="background-color:teal;"><h5>Welcome Create an account here!</h5></nav>
    <div class="Loginbox">
            <div class="container-fluid">

</div>
    

    <div class="row">
        <div class="col-3 col-md col-md-3">
            <div class="container">
                <h4>   Already have an account ?? then</h4> 
              <a href="{% url 'login:login'  %}" class="btn btn-sm btn-primary"><button type="button" class="btn btn-primary btn-sm">Sign In</button></a>
            </div>
                
            </div>
    
                <!--section 2-->
            <div class="col-12 col-sm-6 col-md-6" style="color:rgb(9, 109, 92);">
                    
                <b>
                <div class="container"> 
                    <form method="POST">
                         {% csrf_token %}
                         {{ form|crispy }}
                        <button type="submit" class="btn btn-success">Sign up</button>
                    </form>
                </div></b>
                </div>
                
    
    
                </div>
            
                    
                </div>
               
    
                <div class="col-3 col-md col-md-3">
                    <div class="container" style="color:olive;"><h4></h4>
    
    
                        
        
                        
              
                  
                      </div>
                    </div>
            
          

    
    <br/>
      <footer class="container">
            <p class="float-right"><a href="#">Back to top</a></p>
            <p>&copy; Martin Machua &middot; <a href="#">Privacy</a> Favourite <a href="#">Terms</a></p>
          </footer>
        {% endblock body %}
    

login/templates/login/reset_password.html
{% extends "base.html" %}  
{% load crispy_forms_tags %} 

{{%  block head %}
<title>Reset password</title>
{% endblock head  %}}    
{% block body %}

<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:teal;"><h4>Welcome!</h4></div></nav>
<br/>
<div class="container">
    <div class="col-sm-6 col-sm-offset-3">
        
        <div class="alert alert-warning" role="alert">
            <p>
                Forgotten your password? Enter your email address below, and well email instructions for setting a new one
            </p>
          </div>         

<h2>Reset password</h2>
<br/>
<form method="POST">
   {% csrf_token %}   
   {{form|crispy }}
   <button type="submit" class="btn btn-danger" name="button">reset password</button>
</form>
</div>
</div>
{% endblock body %}

login/templates/login/reset_password_complete.html
{% extends "base.html" %}  

{{%  block head %}
<title>Reset password complete</title>
{% endblock head  %}}

{% block body %}

<nav class="navbar navbar-expand text-white shadow-sm navbar " style="background-color:teal;"><h6> password reset complete!!</h6></nav>
<div class="container">
    <div class="col-sm-6 col-sm-offset-3">
         
<br/>
<h2>Password reset complete</h2>
<p class="lead">Your password reset is complete. You can proceed to login with your new password.
    
</p>
 

<a href="{% url 'login'  %}" class="btn btn-success" role="button">login again</a>

</div>

</div>

{% endblock body %}

login/templates/login/reset_password_confirm.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 

{{%  block head %}
<title>Reset password confirm</title>
{% endblock head  %}}
{% block body %}
<nav class="navbar navbar-expand text-white shadow navbar " style="background-color:teal;"><h5>Welcome to reset your password</h6></div></nav>

<br>
<div class="container">
    <div class="col-sm-6 col-sm-offset-3">
        
        <div class="alert alert-warning" role="alert">
            <p>
                Forgotten your password? 
            </p>
          </div>         

<h2>Enter New password</h2>
<br/>
<form method="POST">
   {% csrf_token %}   
   {{form|crispy }}
   <button type="submit" class="btn btn-danger" name="button">reset password</button>
</form>
</div>
</div>
{% endblock body %}

login/templates/login/reset_password_email.html
{% autoescape off %}

  
 To initiate the password reset process for your {{ user.get_username }} Favourite Account,
click the link below:


{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'login:password_reset_confirm' uidb64=uid token=token  %}
{% endblock reset_link %}


If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The Favourite Team
{% endautoescape %}