agent/urls.py
from django.conf.urls import include, re_path
from .import views
from .views import all_agents, agent, agentadmin ,Post, Messages


app_name = 'agent'

urlpatterns = [
    re_path(r'^all_agents/$', views.all_agents, name='all_agents'),
    re_path(r'^agent/$', views.agent, name='agent'),
    re_path(r'^agentadmin/$', views.agentadmin, name='agentadmin'),
    re_path(r'^post/$', views.Post, name='post'),
    re_path(r'^messages/$', views.Messages, name='messages')

]

home/urls.py
from django.conf.urls import include, re_path
from .import views
from .views import home


app_name = 'home'

urlpatterns = [
    re_path(r'^home/$', views.home, name='home'),
    #re_path(r'^agent/$', views.agent, name='agent')

]

login/urls.py
from django.urls import include, path

from .views import login, client, agent

from django.conf.urls import url
from django.urls import include, re_path
from django.urls import include ,path
from django.contrib.auth.views import (
    login,
    logout,
     password_reset_confirm,
      password_reset,
     password_reset_done,
     password_reset_complete
     )
from django.contrib.auth import views as auth_views
from . import views as myapp_views
from . import views
from  .views import login 

app_name = 'login'

urlpatterns = [

    path('clients/', include(([
        re_path(r'^profile/$',login.ProfileView.as_view(), name='profile'),
        re_path(r'^profile/edit/$', login.edit_profile, name='edit_profile'),
        re_path(r'^change-password/$', login.change_password, name='change_password'),
        re_path(r'^reset-password/$', password_reset,{ 'template_name':
                  'login/reset_password.html','post_reset_redirect':
                  'login:password_reset_done','email_template_name':
                  'login:reset_password_email.html' }, name='reset_password'),
        re_path(r'^reset-password/done/$', password_reset_done, 
                  {'template_name':'login/reset_password_done.html'},
                  name='password_reset_done'),
        re_path(r'^reset-password/confirm/$', password_reset_confirm, name='password_reset_confirm'),

        re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                  password_reset_confirm, {'template_name':
                  'login/reset_password_confirm.html', 'post_reset_redirect':
                  'login:password_reset_complete'},  name='password_reset_confirm'),

        re_path(r'^reset-password/complete/$', password_reset_complete,{'template_name':
                  'login/reset_password_complete.html'}, name='password_reset_complete'),
        re_path(r'^logout/$', logout,{'template_name': 'login/logout.html'}, name='logout'),

        re_path(r'^about/$', login.about, name='about'),
        #re_path(r'^delete/(?P<username>[\w|\W.-]+)/$', views.delete_user, name='delete-user')

    ]))),


    path('agent/', include(([
        #re_path(r'^profile/$',login.ProfileView.as_view(), name='profile'),
        re_path(r'^profile/edit/$', login.edit_profile, name='edit_profile'),
        re_path(r'^change-password/$', login.change_password, name='change_password'),
        
        re_path(r'^reset-password/$',  password_reset,{ 'template_name':
                  'login/reset_password.html','post_reset_redirect':
                  'login:password_reset_done','email_template_name':
                  'login/reset_password_email.html' }, name='reset_password'),
        re_path(r'^reset-password/done/$', password_reset_done, 
                  {'template_name':'login/reset_password_done.html'},
                  name='password_reset_done'),
        re_path(r'^reset-password/confirm/$', password_reset_confirm, name='password_reset_confirm'),
  
        re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                  password_reset_confirm, {'template_name':
                  'login/reset_password_confirm.html', 'post_reset_redirect':
                  'login:password_reset_complete'},  name='password_reset_confirm'),

        re_path(r'^reset-password/complete/$', password_reset_complete,{'template_name':
                  'login/reset_password_complete.html'}, name='password_reset_complete'),
        re_path(r'^logout/$', logout,{'template_name': 'login/logout.html'}, name='logout'),

        re_path(r'^about/$', login.about, name='about')

    ])))
 
]





    

sci/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include ,path ,re_path

from login.views import  client, login, agent

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('login.urls')),
    #path('chat/', include('chat.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', login.SignUpView.as_view(), name='signup'),
    path('accounts/signup/client/', client.ClientSignUpView.as_view(), name='client_signup'),
    path('accounts/signup/agent/', agent.AgentSignUpView.as_view(), name='agent_signup'),
    path('home/', include('home.urls', namespace='home')),
    path('agent/', include('agent.urls', namespace='agent')),
    path('document/', include('document.urls', namespace='document')),
    path('Profile/',include('Profile.urls',namespace='Profile')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

home/models.py
from django.db import models

# Create your models here.

login/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.html import escape, mark_safe
from django.utils import timezone
from sci import settings
from django.db.models.signals import post_save


class User(AbstractUser):
    is_client = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Business_name = models.CharField(max_length=21, default='')
    county = models.CharField(max_length=100, default='')
    sub_county = models.CharField(max_length=100, default='')
    Estate = models.CharField(max_length=100, default='')
    location = models.CharField(max_length=100, default='')
    address = models.CharField(max_length=50, default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to='profile_image', blank=True, default='0')

    def __str__(self):
        return self.user.username


class Client(models.Model):
    
    phone = models.IntegerField(default=0)
    county = models.CharField(max_length=100,blank=True, null=True, default='',choices=(
                                    ('Nairobi', 'Nairobi'),  
                                    ('Nakuru', 'Nakuru')))
    image = models.ImageField(upload_to='profile_image', blank=False ,default='')
    gender = models.CharField(max_length=6,blank=True, null=True, default='',choices=(
                                    ('M', 'Male'),  
                                    ('F', 'Female')))
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.db import transaction
from django.forms.utils import ValidationError
from django.contrib.auth import get_user_model
from login.models import User, Client, Agent


class ClientSignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )
        
        @transaction.atomic
        def save(self, commit=True):
            user = super(ClientSignUpForm, self).save(commit=False)
            User.username = self.cleaned_data['username']
            User.email = self.cleaned_data['email']
            user.is_client = True
            if commit:
                user.save()
            return user



class AgentSignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

        def save(self, commit=True):
            user = super(AgentSignUpForm, self).save(commit=True)
            User.username = self.cleaned_data['username']
            User.email = self.cleaned_data['email']
            user.is_agent = True
            if commit:
                user.save()
            return user



class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password'
        )


class EditAgentForm(UserChangeForm):

    class Meta:
        #model = EditShopForm
        fields = (
            'Business_name',
            'description',
            'image',
            'county',
            'sub_county',
            'estate',
            'location',
            'Address',
            'phone'
            

        )

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home/home.html')

login/views/agent.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator


from login.decorators import client_required, agent_required
from login.models import Agent, User
from django.views.generic import TemplateView , CreateView
from login.forms import AgentSignUpForm


class AgentSignUpView(CreateView):
    template_name = 'registration/signup_form.html'
    model = Agent
    form_class = AgentSignUpForm

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'agent'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('agent:product_list')

login/views/client.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator



from login.decorators import client_required
from login.models import  Client, User
from django.views.generic import TemplateView , CreateView
from login.forms import  ClientSignUpForm


class ClientSignUpView(CreateView):
    template_name = 'registration/signup_form.html'
    model = Client
    form_class = ClientSignUpForm

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'client'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('login:about')

login/views/login.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView

from django.http import Http404
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404
#from django.contrib.auth.forms import RegistrationForm
#from login.forms import ( EditProfileForm)
#from django.contrib.auth.models import User
from ..models import User

from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm#, EditProfileForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from login.forms import  EditProfileForm#, contactForm
#from home.views import Post
#from home.models import  Friend
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
#from login.models import UserProfile
#from shopp.models import Product, Category

from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import get_template




class SignUpView(TemplateView):
    template_name = 'registration/signup.html'

    def home(self, request):
        if request.user.is_authenticated:
            if request.user.is_shop:
                return redirect('login:about')
            else:

            
                return redirect('login:about')
            if request.user.is_client:

                return redirect('login:about')
            
            else:
                return redirect('login:about')
        
        return render(request,'login/about.html')

#    def get(self, request):
#        if request.user.is_authenticated:
#            if request.user.is_client:
##                return redirect('shopp:product_list')
 #           else:
#                return redirect('shopp:product_list')
#        return render(request,'registration/signup.html')




@method_decorator(login_required, name='dispatch')
class ProfileView(TemplateView):
    template_name = 'login/profile.html'
    
    def get(self, request):
       

        try:
            users = User.objects.exclude(id=request.user.id)
            friend = Friend.objects.get(current_user=request.user)
            friends = friend.users.all()

        except:
            users = User.objects.all()
            friends = Friend.objects.all()
        args = {
                 #'user': user,
                 'users': users,
         'friends': friends
        }
        return render(request, self.template_name, args)

    




@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect( 'login:profile' )

    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'login/edit_profile.html', args)
        
@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST,user=request.user )

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)

            return redirect( 'login:profile' )

        else:
            return redirect('/login/change-password')

    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'login/edit_profile.html', args)




def about(request):
    context = locals()
    #template = 'about.html'
    #form = contactForm(request.POST or None)
#
#    if form.is_valid():
#        print( request.POST)
#        context = locals()
    return render(request, 'login/about.html')#,context )
 


@login_required
def login_admin(request):
    return render(request, 'admin/login.html')


@login_required
def delete_user(request, username):
    context = {}
    try:
        u = User.objects.get(username=username)
        u.delete()
        context['msg'] = 'The user is deleted.'       
    except User.DoesNotExist: 
        context['msg'] = 'User does not exist.'
    except Exception as e: 
        context['msg'] = e.message

    return render(request, 'template.html', context=context) 

login/templates/accounts.html
<html>
  <body>

    <h1>Edit your account</h1>

    <hr>

    <h2>Your avatar</h2>

    <input type="file" id="file-input">
    <p id="status">Please select a file</p>
    <img style="border:1px solid gray;width:300px;" id="preview" src="/static/media/default.png">

    <h2>Your information</h2>

    <form method="POST" action="/submit-form/">
      <input type="hidden" id="avatar-url" name="avatar-url" value="/static/media/default.png">
      <input type="text" name="username" placeholder="Username"><br>
      <input type="text" name="full-name" placeholder="Full name"><br><br>

      <hr>
      <h2>Save changes</h2>

      <input type="submit" value="Update profile">
    </form>


    <script type="text/javascript">
    /*
      Function to carry out the actual POST request to S3 using the signed request from the Python app.
    */
    function uploadFile(file, s3Data, url){
      const xhr = new XMLHttpRequest();
      xhr.open('POST', s3Data.url);
      xhr.setRequestHeader('x-amz-acl', 'public-read');
      const postData = new FormData();
      for(key in s3Data.fields){
        postData.append(key, s3Data.fields[key]);
      }
      postData.append('file', file);
      xhr.onreadystatechange = () => {
        if(xhr.readyState === 4){
          if(xhr.status === 200 || xhr.status === 204){
            document.getElementById('preview').src = url;
            document.getElementById('avatar-url').value = url;
          }
          else{
            alert('Could not upload file.');
          }
        }
      };
      xhr.send(postData);
    }
    /*
      Function to get the temporary signed request from the Python app.
      If request successful, continue to upload the file using this signed
      request.
    */
    function getSignedRequest(file){
      const xhr = new XMLHttpRequest();
      xhr.open('GET', `/sign-s3?file-name=${file.name}&file-type=${file.type}`);
      xhr.onreadystatechange = () => {
        if(xhr.readyState === 4){
          if(xhr.status === 200){
            const response = JSON.parse(xhr.responseText);
            uploadFile(file, response.data, response.url);
          }
          else{
            alert('Could not get signed URL.');
          }
        }
      };
      xhr.send();
    }
    /*
       Function called when file input updated. If there is a file selected, then
       start upload procedure by asking for a signed request from the app.
    */
    function initUpload(){
      const files = document.getElementById('file-input').files;
      const file = files[0];
      if(!file){
        return alert('No file selected.');
      }
      getSignedRequest(file);
    }
    /*
       Bind listeners when the page loads.
    */
    (() => {
      document.getElementById('file-input').onchange = initUpload;
    })();
    </script>
  </body>
</html>

login/templates/base.html
 {% load static %}
 <!DOCTYPE html>
 <html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
   
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/infinite.min.js' %}"></script>
    <script src="{% static 'css/app.js'%}"></script>
    
    {% load static %}
  
    <link rel="stylesheet" href="{% static 'login/style.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'agent.css' %}">

   
      {% block head %}
      <title>base</title>
    
      {% endblock %}
      
</head>
<body>


                <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
                        <a class="navbar-brand" style="color:rgb(16, 73, 68)" href="#"><h5><b>Notehub</b></h5></a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                {% if user.is_authenticated %}      
                        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                                <li class="nav-item active mr-auto">
                                   <a class="nav-link" href="{% url  'home:home' %}">Home</a>
                                </li>
                               <!-- <li class="nav-item active mr-auto">
                                        <a class="nav-link mr-auto" href="{ % url  'home:home' %}">Home<span class="sr-only">(current)</span></a>
                                    </li>-->
                                  <li class="nav-item active mr-auto">
                                        <a class="nav-link" href="{% url  'agent:agent' %}">agents</a>
                                  </li>
                              
                               
                          </ul>



                                      <!-- Example single small button -->
               <li class="nav item">
                      <div class="dropdown">
                              <a class="btn btn-sm btn-light dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        
                                       account
                                    
                              </a>
            
              <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                
                  
                  <a class="dropdown-item" href="{ % url 'login:profile' %}">
                            View Profile                 
                  </a>
                 
                                
                                {% if user.is_agent %}
                                    <a class="dropdown-item"  href="{ % url  'Profile:Shopadmin' %}">agent admin</a>
                                 
                                
                                    
                                  {% else %}

                                  {% endif %}
                                 




                  <a class="dropdown-item" href="{ % url 'login:logout' %}">Logout</a>
                 
              </div>
            </div>
          </li>
   
              




                                <form   class="form-inline my-2 my-lg-0" action='{ % url 'shopp:product_list' %}'>
                                
                                   
                                        <input  type="search" class="form-control outline-info btn-sm mr-sm-2"  placeholder="Search" name='q'>
                                     {% csrf_token %}      
                                        <button class="btn btn-dark btn-sm btn-rounded my-2 my-sm-0" type="submit">Search</button>
                                      </form>
                                {% else  %}
                          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

                                   

                                   <div class="btn-group">
                                <button class="btn text-black btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                         account →
                                </button>
                                <div class="dropdown-menu">
          
                                    <a class="dropdown-item" href="{% url 'login'  %}">sign in</a>
                                    <a class="dropdown-item" href="{% url 'signup'  %}">sign up</a>
                                    <a class="dropdown-item" href="{ % url 'login:reset_password'  %}">reset-password </a>
                                    <a class="dropdown-item" href="{ % url 'Profile:about' %}">about</a>

                                </div>
                                </div>

                                   
                          </ul>           
                        
                                    <!--<form   class="form-inline my-2 my-lg-0" action='{ % url 'shopp:product_list' %}'>
                                
                                       {% csrf_token %}  
                                        <input  type="search" class="form-control btn-sm mr-sm-2"  placeholder="Search" name='q'>
                                     {% csrf_token %}      
                                        <button class="btn btn-sm btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                                      </form>-->
                        

              
           
                              
                             {% endif %}
                        </div>
                      </nav>  
       
    {% block body%}
    <h1>Base</h1>
    {% endblock %}





    <!-- Optional JavaScript -->
   <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <script src="{% static 'agent.js' %}"></script>
  

</body>
</html>

login/templates/home.html
{% extends 'base.html' %}

{% block body %}
  <h2>Welcome to Favourite  <span class="icon-emo-happy"></span></h2>
  <p class="lead">
    If you already have an account, go ahead and <a href="{% url 'login' %}">log in</a>. If you are new , get started
    by creating a <a href="{% url 'client_signup' %}">student account</a> or a <a href="{% url 'agent_signup' %}">teacher account</a>.
  </p>
  <hr>
  
{% endblock body %}